# Generated by Django 3.1.2 on 2020-10-20 20:19

import candidates.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('resume', models.FileField(blank=True, null=True, upload_to=candidates.models.upload_path)),
            ],
        ),
    ]
