# Generated by Django 3.1.2 on 2020-10-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Phone_Screen', 'Phone Screen'), ('On_site', 'On site'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=30),
        ),
    ]
